In [7]:
%pip install sqlalchemy
%pip install pandas
import pandas as pd
from sqlalchemy import create_engine
# Postgres username, password, and database name
POSTGRES_ADDRESS = 'localhost' ## INSERT YOUR DB ADDRESS IF IT'S NOT ON PANOPLY
POSTGRES_PORT = '5432'
POSTGRES_USERNAME = 'postgres' ## CHANGE THIS TO YOUR PANOPLY/POSTGRES USERNAME
POSTGRES_PASSWORD = 'admin' ## CHANGE THIS TO YOUR PANOPLY/POSTGRES PASSWORD POSTGRES_DBNAME = 'database' ## CHANGE THIS TO YOUR DATABASE NAME
# A long string that contains the necessary Postgres login information
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'.format(username=POSTGRES_USERNAME
                                                                                        ,password=POSTGRES_PASSWORD
                                                                                        ,ipaddress=POSTGRES_ADDRESS
                                                                                        ,port=POSTGRES_PORT
                                                                                        ,dbname='testfligoo'))
# Create the connection
cnx = create_engine(postgres_str)

Requirement already satisfied: sqlalchemy in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from sqlalchemy) (1.1.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.2; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\javie\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (1.4.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (1.22.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\javie\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.2; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\javie\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

In [12]:
pd.read_sql_query('''SELECT * FROM processed.testdata LIMIT 10;''', cnx)

,flight_date,flight_status,departure_airport,departure_timezone,arrival_airport,arrival_timezone,arrival_terminal,airline_name,flight_number,timestamp
0,2022-03-28,active,Matsuyama,Asia-Tokyo,Haneda Airport,Asia-Tokyo,2,ANA,582,2022-03-27
1,2022-03-28,active,Shuangliu,Asia-Shanghai,Bangalore International Airport,Asia-Kolkata,1,Lufthansa Cargo,8411,2022-03-27
2,2022-03-28,active,Eltari,Asia-Dili,Soekarno-Hatta International,Asia-Jakarta,2,Batik Air,6541,2022-03-27
3,2022-03-28,active,Alice Springs,Australia-Darwin,Adelaide International Airport,Australia-Adelaide,1,Alliance Airlines,1955,2022-03-27
4,2022-03-28,active,Zamboanga International,Asia-Manila,Ninoy Aquino International,Asia-Manila,3,Cebu Pacific Air,862,2022-03-27
5,2022-03-28,active,Soekarno-Hatta International,Asia-Jakarta,Sultan Aji Muhamad Sulaiman Airport\n,None,1,Lion Air,760,2022-03-27
6,2022-03-28,active,Soekarno-Hatta International,Asia-Jakarta,Sultan Aji Muhamad Sulaiman Airport\n,None,1,None,6313,2022-03-27
7,2022-03-28,active,Soekarno-Hatta International,Asia-Jakarta,Lombok International,Asia-Makassar,2,Batik Air,6656,2022-03-27
8,2022-03-28,active,Soekarno-Hatta International,Asia-Jakarta,Juanda,Asia-Jakarta,2,Batik Air,6370,2022-03-27
9,2022-03-28,active,Soekarno-Hatta International,Asia-Jakarta,Sjamsudin Noor,Asia-Makassar,1,Lion Air,528,2022-03-27